#!/bin/sh /etc/rc.common

START=19
boot() {
    if grep -qe "sw2.*in  hi" /sys/kernel/debug/gpio ; then
        if grep -qe "sw1.*in  hi" /sys/kernel/debug/gpio ; then
            # AP
            logger AP
            #action here:

        else
            # WISP
            logger WISP
            #action here:

        fi
    else
        # 3G
        logger 3G
        #action here:

    fi
}
